zoontek/react-native-bootsplash

- android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java
If you are trying to use react native firebase notifications you cant use 
```
const notificationOpen: NotificationOpen = await firebase.notifications().getInitialNotification();
if (notificationOpen) {
// App was opened by a notification
// Get the action triggered by the notification being opened
const action = notificationOpen.action;
// Get information about the notification that was opened
const notification: Notification = notificationOpen.notification;
}
```
because splash activity start on first load and it doesnt send the data to MainActivity.
> Fix Sending First Start Data To MainActivity

- android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java
current implementation will return the application id with suffix, which is not correct, because `MainActivity` belong to the main package id
current implementation:
```
nl.elements.app.debug.MainActivity
```
correct implementation.
```
nl.elements.app.MainActivity
```
> fix(android): get the main application id without suffix

- package.json
Otherwise it isn't installed in projects using this library, causing generation command to fail.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zoontek/react-native-bootsplash/44)
> fix(config): move jimp to dependencies

- README.md
RN projects do not have `android:exported="true"` by default
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/zoontek/react-native-bootsplash/45)
> Explain the need to export MainActivity

- README.md
Use bootsplash_logo image instead of ic_launcher to fix " App stopped " issue on Android
> Docs : update splash screen image resource

- android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java
Hello! 
Is any reason why you attach action and data only in case of intent's `ACTION_VIEW` action? This breaks intents that are come via [notification action](https://developer.android.com/training/notify-user/build-notification#Actions) press, so they get to the MainActivity without vital `action` identifier.
> Add support for custom notification actions

- README.md
- lib/generate.js
- package.json
- react-native.config.js
- scripts/generate.js
- yarn.lock
Fixes issue #51 by adding an argument-based system for defining bootsplash components.
Key files:
* `react-native.config.js` - defines the command for running
* `lib/generate.js` exports a function for running the generator for extensiblility
* `scripts/generate.js` now uses the exported version of generate
* `README.md` references the new CLI system
Also adding functionality to automatically add the storyboard to the ios Xcode package, and make it the launchscreen provider, addressing issue #85
> Add React-Native command plugin: "generate-bootsplash"

- RNBootSplash.podspec
Latest Xcode 12 fails to build while without a module to depend on React-Core directly hence this change is necessary for all native modules on iOS. For more details please check: facebook/react-native#29633 
Xcode 12 for testing
| iOS     |    ✅  |
| Android |    ❌     |
> fix: Xcode 12 compatibility

- android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java
Needed to redirect to custom activity package/name
In order to maintain compatibility with previous versions of the app, we need to use an activity-alias. In that case we the logic to get the main activity to redirect will fail as the activity-alias doesn't create a backing class.
No user-facing changes
| iOS     |    ❌     |
| Android |    ✅    |
- [ x] I have tested this on a device and a simulator
- [ n/a] I updated the typed files (TS and Flow)
- [ n/a] I added a sample use of the API in the example project (`example/App.js`)
> Allow extending with custom activity class [Android]

- android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java
Fixes #198
Use https://github.com/slaci/RnBootsplashExample for testing.
Just open the app and see which logo is shown. A logo with "dark" label should be always visible regardless of the phone's setting. In the example app, the logo will be hidden after 3 seconds after app start.
Android devices which do not support night mode (maybe < 10) will continue to show the light mode logo as before (tested in api level 26 emulator). It only fixes situations when different variant of native drawables are used (not only dark mode exists, it is possible to create images for eg. landscape orientation too).
| iOS     |    ❌     |
| Android |    ✅    |
> [android] Use activity as context instead of application

- android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java
The intent type was not being forwarded to the MainActivity. This was a problem when I was trying to receive sharing intents in my RN app which uses this lovely library. 
Forward the intent type to MainActivity.
I used the intent methods 'setType' and 'getType'
It impacts the intent forwarding to MainActivity
Android device and/or emulator, logger
Log incoming activity that a type (the example I was using was receiving a Send activity with type 'text'). Before this pr the type will be null. After this pr, the type will be the correct MIME type ('text' or 'image') etc. More information https://developer.android.com/reference/android/content/Intent#getType() and https://developer.android.com/reference/android/content/Intent#setType(java.lang.String)
| ------- | …
> feat: forward intent type to mainActivity

- android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashActivity.java
Explain the **motivation** for making this change: here are some points to help you:
* In #205 I forwarded the intent type to MainActivity without checking if the type was null. Forwarding a 'null' type to MainActivity breaks [React-Navigation deeplinking](https://github.com/zoontek/react-native-bootsplash/pull/205#issuecomment-779829726 (thanks @exentrich for heads up!)
). So this pr checks if type is null and only sets it if it is non-null.
Without checking for null type, (ie as of #205 ) `adb shell am start -W -a android.intent.action.VIEW -d [deeplink] [packagename]` does not work with React-Navigation deeplinks
With this pr `adb shell am start -W -a android.intent.action.VIEW -d [deeplink] [packagename]` does work for React-Navigation deeplinks
App with deeplinks configured by …
> fix: only forward non-null intent type to MainActivity

- ReactNativeBootsplash.res
Please poke me next time if you add features that need bindings :)
Title is explicit
Tested locally on my project
Some trust in @MoOx 
Currently we cannot not use promise based API with ReScript 
| iOS     |    ✅     |
| Android |    ✅     |
>  Update ReScript bindings for 3.1

- ios/RNBootSplash.m
If the app's window has not been configured with a root view controller or made key, `RCTPresentedViewController()` returns `nil`, and RNBootSplash is left in an inconsistent state where the splash view cannot be hidden. If this happens, log an error to help users debug the issue.
| iOS     |    ✅     |
| Android |    ❌     |
> Warn if RNBootSplash is initialised before rootViewController is set

- README.md
To prevent a crash when using `react-native-screens`, you must pass `null` to `super.onCreate` in `MainActivity`. [Reference](https://github.com/software-mansion/react-native-screens#android)
This PR updates the Android example in the README to pass `null` to `super.onCreate`, because I assume most React Native apps use `react-native-screens`. Without this change, a developer might copy the `react-native-bootsplash` example code into their app, accidentally overwriting the `super.onCreate(null)` call that is needed to prevent the crash.
Not sure if a test plan is necessary for this change. If it is let me know and I will attempt to fill in this section.
| iOS     |    ✅    |
| Android |    ✅     |
> README: prevent react-native-screens crash

- MIGRATION.md
- README.md
Leaving the build.gradle alone, this is just tiny grammar tweaks, and mentioning API21 per #275 
I also specifically called out the `android:exported` need since that hasn't even landed on the react-native template yet and people may be unaware - I've been busy patching it in other places and most people are unaware...  https://github.com/facebook/react-native/pull/32540
> docs(v4): mention API21 possible but weak support, grammar

- README.md
Adds SVG instructions to README as per out conversation here: https://github.com/zoontek/react-native-bootsplash/issues/313#issuecomment-1030285259
Not needed.
N/A
N/A
| iOS     |    ✅    |
| Android |    ✅     |
> Add SVG instructions to README

- README.md
Prevent `Multiple SVG files are only allowed for PDF and (E)PS output.` when generating PNG from SVG file.
| iOS     |    ✅❌     |
| Android |    ✅❌     |
> Docs: Add `-o` on Using an SVG section

- example/package.json
- example/yarn.lock
- package.json
- yarn.lock
Jimp 0.16.2 includes the latest jpeg-js, resolving cve-2022-25851 and removing the need to pin jpeg-js to 0.4.4
This PR bumps jimp version and removes the pinned dependencies, including in the example
yarn or npm install and confirm no security warnings
| iOS     |    ✅❌     |
| Android |    ✅❌     |
> Bump jimp from 0.16.1 to 0.16.2

- README.md
- android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModule.java
- ios/RNBootSplash.m
- package.json
- src/index.ts
This feature implements a custom duration for the splash screen fade out.
The parameter is optional, with the default being 220ms, as it was already before, making it backwards compatible without any changes for the current consumers.
Android emulator & iOS simulator is enough.
```import * as React from "react";
import {
View,
} from "react-native";
import * as BootSplash from "react-native-bootsplash";
export const App = () => {
React.useEffect(() => {
BootSplash.hide({fade:true, duration: 2500}); // Edit duration
}, []);
return (
<View />)
};
```
| -------- | :---------: |
| iOS        |     ✅          |
| Android |    ✅           |
The current example project isn't "visually" compatible with this feature, as the logo is hidden from JS.
> feature: Implement custom fade out duration

- README.md
- react-native.config.js
Add functionality to generate assets for Android and iOS separately. It's useful when an app has 2 different splash screens for each platform or is developed only for iOS or Android. It impacts CLI script options.
- yarn install
- run CLI script inside example folder and try to generate assets for iOS or Android separately.
| iOS     |    ✅    |
| Android |    ✅     |
> feat: Adds conditional assets generations

- android/build.gradle
Hey @zoontek 👋  - for AGP8+, if you use build config you have to opt-in to it now, it is turned off by default
So AGP8+ support for this module needs more than just the namespace, it also needs a little build.gradle tweak to enable build config
It is similar to changes I needed to do as react-native-firebase maintainer --> https://github.com/invertase/react-native-firebase/commit/b52d0ce6723c077190618641ce0f33ced9fd4090
With apologies, you have to alter an app that integrates this module to use android gradle plugin 8, it's difficult to do that in repos I'm proposing these changes in because bumping to android gradle plugin 8 requries a large amount of transitive dependency changes in CI - the example app here is still depending on AGP7+ so doesn't show it
I have integrated this in an app …
> fix(android): android gradle plugin 8 compatibility

- README.md
add missing example for android when using react native 0.73.0
> add example for react native 0.73.0

- android/src/main/java/com/zoontek/rnbootsplash/RNBootSplashModuleImpl.java
- android/src/newarch/com/zoontek/rnbootsplash/RNBootSplashModule.java
- android/src/oldarch/com/zoontek/rnbootsplash/RNBootSplashModule.java
Fix for #552, have exposed a `deInit` method which needs to be called when the `onDestroy` of activity is called. 
There is no larger impact, have only reset a few variables upon activity destroy which are recreated when init is called again.
Sample repro - https://github.com/Protino/splash-flash-repro
Add this patch to the repro, re-run the scenario, and verify splash screen doesn't flash
| iOS     |    ✅  (Fix NA)   |
| Android |    ✅    |
> Fixes #552; de-initialize RNBootSplash on activity destroy

- README.md
- react-native.config.js
- src/generate.ts
Realization of the choice of whether the project is bare or expo. 
Added new cli options to specify whether the project is an expo or bare with expo modules
See request feature issue https://github.com/zoontek/react-native-bootsplash/issues/597
* create app using `npx create-expo-app@latest --template bare-minimum`
* install `react-native-bootsplash`
* run `react-native generate-bootsplash  icon --expo=false`
run `react-native generate-bootsplash  icon --expo=false`
Expected result:
```
🤖  Android
android/app/main/res/drawable-mdpi/bootsplash_logo.png (288x288)
android/app/main/res/drawable-hdpi/bootsplash_logo.png (432x432)
android/app/main/res/drawable-xhdpi/bootsplash_logo.png (576x576)
android/app/main/res/drawable-xxhdpi/bootsplash_logo.png (864x864) …
```
> Ability to specify whether the project is bare or expo

- ios/RNBootSplash.mm
Closes https://github.com/zoontek/react-native-bootsplash/issues/619
Run example iOS app in xcode with Main thread breakpoint enabled.
Expected Behavior:
No breakpoint should be thrown.
| iOS     |    ✅     |
| Android |    ❌     |
> Running RCTKeyWindow on main thread

- src/expo.ts
Calling super will allow expo modules to work properly when using customizeRootView in expoAppDelegateSubscribers
| iOS     |    ✅   |
| Android |    ❌     |
> fix: call super in customizeRootView

- src/expo.ts
While upgrading the React Conf app to SDK 53 today, I encountered the following error:
Following [this](https://github.com/expo/expo/pull/36303) change, config plugins should be added via the `ReactNativeDelegate`.
Verified on the React Conf app.
- `yarn build`
-  copy the new `dist` folder the React Conf app ([this](https://github.com/expo/react-conf-app/tree/%40kadikraman/upgrade-sdk-53) is the branch I used)
- `npx expo run:ios`
Checkout [this](https://github.com/expo/react-conf-app/tree/%40kadikraman/upgrade-sdk-53) on the React Conf app repo.
- `yarn` in the React Conf project
- `yarn build` in this project
-  copy the new `dist` folder to the `node_modules` (or use `yalc` to publish it locally)
- `npx expo run:ios`
| iOS     |    ✅ …
> Update expo config plugin to use ReactNativeDelegate in SDK 53

- src/expo.ts
While upgrading to expo SDK 53 using static libraries (`expo-build-properties` with `ios.useFrameworks: "static"`), we ran into the following error in the `AppDelegate.swift` when building: 
This PR fixes this issue. 
It can be reproduced on the react-conf-app branch upgrading to SDK 53.
Update `app.config.js` on [this branch](https://github.com/expo/react-conf-app/tree/%40kadikraman/upgrade-sdk-53) to add the following options to the `expo-build-properties` config plugin: 
```
[
"expo-build-properties",
{
ios: {
useFrameworks: "static",
},
},
],
```
iOS build will fail 
Applying the change in this PR (changing `customize` signature from `public override func customize(_ rootView: RCTRootView)` to `public override func customize(_ rootView: UIView)` in the `AppDelegate` will let you build …
> fix: customize root view override signature in config plugin
